konq.newtab: launch new konqueror if none present

diff --git a/util/konqueror-newtab b/util/konqueror-newtab
--- a/util/konqueror-newtab
+++ b/util/konqueror-newtab
@@ -1,11 +1,17 @@
 #!/bin/sh
 
-# Print message to stderr and exit
-function fail { echo $@ >&2; exit 1; }
+# Number of konquerors running.
+NKONQ= $(dcop | grep konqueror -c)
 
-# Check number of konquerors running. If more than one - fail.
-# As cannot choose
-[ $(dcop | grep konqueror -c) == '1' ] || fail "More than one konqueror opened"
+if [ $NKONQ == '0' ] ; then
+    # Create new broser instance 
+    konqueror $1
+elif [ $NCONQ == '1' ]; then
+    # Open link in new tab 
+    dcop $(dcop | grep konqueror) konqueror-mainwindow#1 newTab $1
+else
+    # More than one konqueror opened. Fail as we cannot choose
+    "More than one konqueror opened" >&2
+    exit 1
+fi
 
-# Open link in new tab 
-dcop $(dcop | grep konqueror) konqueror-mainwindow#1 newTab $1
